# Generated by cpp11: do not edit by hand

cpp11_add_vec_for_ <- function(x, num){
  .Call("_cpp11test_cpp11_add_vec_for_" , x, num)
}

data_frame_ <- function(){
  .Call("_cpp11test_data_frame_" )
}

grow_ <- function(n){
  .Call("_cpp11test_grow_" , n)
}

cpp11_insert_ <- function(num_sxp){
  .Call("_cpp11test_cpp11_insert_" , num_sxp)
}

gibbs_cpp <- function(N, thin){
  .Call("_cpp11test_gibbs_cpp" , N, thin)
}

gibbs_cpp2 <- function(N, thin){
  .Call("_cpp11test_gibbs_cpp2" , N, thin)
}

gibbs_rcpp <- function(N, thin){
  .Call("_cpp11test_gibbs_rcpp" , N, thin)
}

gibbs_rcpp2 <- function(N, thin){
  .Call("_cpp11test_gibbs_rcpp2" , N, thin)
}

cpp11_release_ <- function(n){
  invisible(.Call("_cpp11test_cpp11_release_" , n))
}

rcpp_release_ <- function(n){
  invisible(.Call("_cpp11test_rcpp_release_" , n))
}

cpp11_safe_ <- function(x_sxp){
  .Call("_cpp11test_cpp11_safe_" , x_sxp)
}

sum_int_for_ <- function(x){
  .Call("_cpp11test_sum_int_for_" , x)
}

rcpp_sum_dbl_for_ <- function(x_sxp){
  .Call("_cpp11test_rcpp_sum_dbl_for_" , x_sxp)
}

rcpp_sum_dbl_foreach_ <- function(x_sxp){
  .Call("_cpp11test_rcpp_sum_dbl_foreach_" , x_sxp)
}

rcpp_sum_dbl_accumulate_ <- function(x_sxp){
  .Call("_cpp11test_rcpp_sum_dbl_accumulate_" , x_sxp)
}

rcpp_grow_ <- function(n_sxp){
  .Call("_cpp11test_rcpp_grow_" , n_sxp)
}

sum_dbl_for_ <- function(x){
  .Call("_cpp11test_sum_dbl_for_" , x)
}

sum_dbl_for2_ <- function(x_sxp){
  .Call("_cpp11test_sum_dbl_for2_" , x_sxp)
}

sum_dbl_for3_ <- function(x_sxp){
  .Call("_cpp11test_sum_dbl_for3_" , x_sxp)
}

sum_dbl_foreach_ <- function(x){
  .Call("_cpp11test_sum_dbl_foreach_" , x)
}

sum_dbl_foreach2_ <- function(x_sxp){
  .Call("_cpp11test_sum_dbl_foreach2_" , x_sxp)
}

sum_dbl_accumulate_ <- function(x){
  .Call("_cpp11test_sum_dbl_accumulate_" , x)
}

sum_dbl_accumulate2_ <- function(x_sxp){
  .Call("_cpp11test_sum_dbl_accumulate2_" , x_sxp)
}


