# Generated by cpp11: do not edit by hand

cpp11_add_vec_for_ <- function(x, num) {
  .Call("_cpp11test_cpp11_add_vec_for_", x, num, PACKAGE = "cpp11test")
}

data_frame_ <- function() {
  .Call("_cpp11test_data_frame_", PACKAGE = "cpp11test")
}

remove_altrep <- function(x) {
  .Call("_cpp11test_remove_altrep", x, PACKAGE = "cpp11test")
}

upper_bound <- function(x, breaks) {
  .Call("_cpp11test_upper_bound", x, breaks, PACKAGE = "cpp11test")
}

findInterval2 <- function(x, breaks) {
  .Call("_cpp11test_findInterval2", x, breaks, PACKAGE = "cpp11test")
}

findInterval2_5 <- function(x, breaks) {
  .Call("_cpp11test_findInterval2_5", x, breaks, PACKAGE = "cpp11test")
}

findInterval3 <- function(x, breaks) {
  .Call("_cpp11test_findInterval3", x, breaks, PACKAGE = "cpp11test")
}

findInterval4 <- function(x, breaks) {
  .Call("_cpp11test_findInterval4", x, breaks, PACKAGE = "cpp11test")
}

grow_ <- function(n) {
  .Call("_cpp11test_grow_", n, PACKAGE = "cpp11test")
}

cpp11_insert_ <- function(num_sxp) {
  .Call("_cpp11test_cpp11_insert_", num_sxp, PACKAGE = "cpp11test")
}

gibbs_cpp <- function(N, thin) {
  .Call("_cpp11test_gibbs_cpp", N, thin, PACKAGE = "cpp11test")
}

gibbs_cpp2 <- function(N, thin) {
  .Call("_cpp11test_gibbs_cpp2", N, thin, PACKAGE = "cpp11test")
}

gibbs_rcpp <- function(N, thin) {
  .Call("_cpp11test_gibbs_rcpp", N, thin, PACKAGE = "cpp11test")
}

gibbs_rcpp2 <- function(N, thin) {
  .Call("_cpp11test_gibbs_rcpp2", N, thin, PACKAGE = "cpp11test")
}

row_sums <- function(x) {
  .Call("_cpp11test_row_sums", x, PACKAGE = "cpp11test")
}

protect_one_ <- function(x, n) {
  invisible(.Call("_cpp11test_protect_one_", x, n, PACKAGE = "cpp11test"))
}

protect_one_sexp_ <- function(x, n) {
  invisible(.Call("_cpp11test_protect_one_sexp_", x, n, PACKAGE = "cpp11test"))
}

protect_one_cpp11_ <- function(x, n) {
  invisible(.Call("_cpp11test_protect_one_cpp11_", x, n, PACKAGE = "cpp11test"))
}

protect_one_preserve_ <- function(x, n) {
  invisible(.Call("_cpp11test_protect_one_preserve_", x, n, PACKAGE = "cpp11test"))
}

protect_many_ <- function(n) {
  invisible(.Call("_cpp11test_protect_many_", n, PACKAGE = "cpp11test"))
}

protect_many_cpp11_ <- function(n) {
  invisible(.Call("_cpp11test_protect_many_cpp11_", n, PACKAGE = "cpp11test"))
}

protect_many_sexp_ <- function(n) {
  invisible(.Call("_cpp11test_protect_many_sexp_", n, PACKAGE = "cpp11test"))
}

protect_many_preserve_ <- function(n) {
  invisible(.Call("_cpp11test_protect_many_preserve_", n, PACKAGE = "cpp11test"))
}

protect_many_rcpp_ <- function(n) {
  invisible(.Call("_cpp11test_protect_many_rcpp_", n, PACKAGE = "cpp11test"))
}

cpp11_release_ <- function(n) {
  invisible(.Call("_cpp11test_cpp11_release_", n, PACKAGE = "cpp11test"))
}

rcpp_release_ <- function(n) {
  invisible(.Call("_cpp11test_rcpp_release_", n, PACKAGE = "cpp11test"))
}

cpp11_safe_ <- function(x_sxp) {
  .Call("_cpp11test_cpp11_safe_", x_sxp, PACKAGE = "cpp11test")
}

sum_int_for_ <- function(x) {
  .Call("_cpp11test_sum_int_for_", x, PACKAGE = "cpp11test")
}

rcpp_sum_dbl_for_ <- function(x_sxp) {
  .Call("_cpp11test_rcpp_sum_dbl_for_", x_sxp, PACKAGE = "cpp11test")
}

rcpp_sum_dbl_foreach_ <- function(x_sxp) {
  .Call("_cpp11test_rcpp_sum_dbl_foreach_", x_sxp, PACKAGE = "cpp11test")
}

rcpp_sum_dbl_accumulate_ <- function(x_sxp) {
  .Call("_cpp11test_rcpp_sum_dbl_accumulate_", x_sxp, PACKAGE = "cpp11test")
}

rcpp_grow_ <- function(n_sxp) {
  .Call("_cpp11test_rcpp_grow_", n_sxp, PACKAGE = "cpp11test")
}

sum_dbl_for_ <- function(x) {
  .Call("_cpp11test_sum_dbl_for_", x, PACKAGE = "cpp11test")
}

sum_dbl_for2_ <- function(x_sxp) {
  .Call("_cpp11test_sum_dbl_for2_", x_sxp, PACKAGE = "cpp11test")
}

sum_dbl_for3_ <- function(x_sxp) {
  .Call("_cpp11test_sum_dbl_for3_", x_sxp, PACKAGE = "cpp11test")
}

sum_dbl_foreach_ <- function(x) {
  .Call("_cpp11test_sum_dbl_foreach_", x, PACKAGE = "cpp11test")
}

sum_dbl_foreach2_ <- function(x_sxp) {
  .Call("_cpp11test_sum_dbl_foreach2_", x_sxp, PACKAGE = "cpp11test")
}

sum_dbl_accumulate_ <- function(x) {
  .Call("_cpp11test_sum_dbl_accumulate_", x, PACKAGE = "cpp11test")
}

sum_dbl_accumulate2_ <- function(x_sxp) {
  .Call("_cpp11test_sum_dbl_accumulate2_", x_sxp, PACKAGE = "cpp11test")
}
