# Generated by cpp11: do not edit by hand

cpp11_add_vec_for_ <- function(x, num) {
  .Call(`_cpp11test_cpp11_add_vec_for_`, x, num)
}

data_frame_ <- function() {
  .Call(`_cpp11test_data_frame_`)
}

my_stop_n1fmt <- function(mystring) {
  invisible(.Call(`_cpp11test_my_stop_n1fmt`, mystring))
}

my_stop_n2fmt <- function(mystring, myarg) {
  invisible(.Call(`_cpp11test_my_stop_n2fmt`, mystring, myarg))
}

my_warning_n1fmt <- function(mystring) {
  invisible(.Call(`_cpp11test_my_warning_n1fmt`, mystring))
}

my_warning_n2fmt <- function(mystring, myarg) {
  invisible(.Call(`_cpp11test_my_warning_n2fmt`, mystring, myarg))
}

my_message_n1fmt <- function(mystring) {
  invisible(.Call(`_cpp11test_my_message_n1fmt`, mystring))
}

my_message_n2fmt <- function(mystring, myarg) {
  invisible(.Call(`_cpp11test_my_message_n2fmt`, mystring, myarg))
}

my_stop <- function(mystring, myarg) {
  invisible(.Call(`_cpp11test_my_stop`, mystring, myarg))
}

my_stop_n1 <- function(mystring) {
  invisible(.Call(`_cpp11test_my_stop_n1`, mystring))
}

my_warning <- function(mystring, myarg) {
  invisible(.Call(`_cpp11test_my_warning`, mystring, myarg))
}

my_warning_n1 <- function(mystring) {
  invisible(.Call(`_cpp11test_my_warning_n1`, mystring))
}

my_message <- function(mystring, myarg) {
  invisible(.Call(`_cpp11test_my_message`, mystring, myarg))
}

my_message_n1 <- function(mystring) {
  invisible(.Call(`_cpp11test_my_message_n1`, mystring))
}

remove_altrep <- function(x) {
  .Call(`_cpp11test_remove_altrep`, x)
}

upper_bound <- function(x, breaks) {
  .Call(`_cpp11test_upper_bound`, x, breaks)
}

findInterval2 <- function(x, breaks) {
  .Call(`_cpp11test_findInterval2`, x, breaks)
}

findInterval2_5 <- function(x, breaks) {
  .Call(`_cpp11test_findInterval2_5`, x, breaks)
}

findInterval3 <- function(x, breaks) {
  .Call(`_cpp11test_findInterval3`, x, breaks)
}

findInterval4 <- function(x, breaks) {
  .Call(`_cpp11test_findInterval4`, x, breaks)
}

grow_ <- function(n) {
  .Call(`_cpp11test_grow_`, n)
}

cpp11_insert_ <- function(num_sxp) {
  .Call(`_cpp11test_cpp11_insert_`, num_sxp)
}

gibbs_cpp <- function(N, thin) {
  .Call(`_cpp11test_gibbs_cpp`, N, thin)
}

gibbs_cpp2 <- function(N, thin) {
  .Call(`_cpp11test_gibbs_cpp2`, N, thin)
}

gibbs_rcpp <- function(N, thin) {
  .Call(`_cpp11test_gibbs_rcpp`, N, thin)
}

gibbs_rcpp2 <- function(N, thin) {
  .Call(`_cpp11test_gibbs_rcpp2`, N, thin)
}

row_sums <- function(x) {
  .Call(`_cpp11test_row_sums`, x)
}

col_sums <- function(x) {
  .Call(`_cpp11test_col_sums`, x)
}

protect_one_ <- function(x, n) {
  invisible(.Call(`_cpp11test_protect_one_`, x, n))
}

protect_one_sexp_ <- function(x, n) {
  invisible(.Call(`_cpp11test_protect_one_sexp_`, x, n))
}

protect_one_cpp11_ <- function(x, n) {
  invisible(.Call(`_cpp11test_protect_one_cpp11_`, x, n))
}

protect_one_preserve_ <- function(x, n) {
  invisible(.Call(`_cpp11test_protect_one_preserve_`, x, n))
}

protect_many_ <- function(n) {
  invisible(.Call(`_cpp11test_protect_many_`, n))
}

protect_many_cpp11_ <- function(n) {
  invisible(.Call(`_cpp11test_protect_many_cpp11_`, n))
}

protect_many_sexp_ <- function(n) {
  invisible(.Call(`_cpp11test_protect_many_sexp_`, n))
}

protect_many_preserve_ <- function(n) {
  invisible(.Call(`_cpp11test_protect_many_preserve_`, n))
}

protect_many_rcpp_ <- function(n) {
  invisible(.Call(`_cpp11test_protect_many_rcpp_`, n))
}

cpp11_release_ <- function(n) {
  invisible(.Call(`_cpp11test_cpp11_release_`, n))
}

rcpp_release_ <- function(n) {
  invisible(.Call(`_cpp11test_rcpp_release_`, n))
}

notroxcpp1_ <- function(x) {
  .Call(`_cpp11test_notroxcpp1_`, x)
}

#' @title Roxygenise C++ function II
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 2.0 to a double.
#' @export
#' @examples roxcpp2_(1.0)
roxcpp2_ <- function(x) {
	.Call(`_cpp11test_roxcpp2_`, x)
}

#' @title Roxygenise C++ function III
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 3.0 to a double.
#' @export
#' @examples roxcpp3_(1.0)
roxcpp3_ <- function(x) {
	.Call(`_cpp11test_roxcpp3_`, x)
}

#' @title Roxygenise C++ function IV
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 4.0 to a double.
#' @export
#' @examples roxcpp4_(1.0)
roxcpp4_ <- function(x) {
	.Call(`_cpp11test_roxcpp4_`, x)
}

#' @title Roxygenise C++ function V
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 5.0 to a double.
#' @export
#' @examples roxcpp5_(1.0)
roxcpp5_ <- function(x) {
	.Call(`_cpp11test_roxcpp5_`, x)
}

notroxcpp6_ <- function(x) {
  .Call(`_cpp11test_notroxcpp6_`, x)
}

#' @title Roxygenise C++ function VII
#' @param x numeric value
#' @description Dummy function to test roxygen2. It adds 7.0 to a double.
#' @export
#' @examples roxcpp7_(1.0)
roxcpp7_ <- function(x) {
	.Call(`_cpp11test_roxcpp7_`, x)
}

cpp11_safe_ <- function(x_sxp) {
  .Call(`_cpp11test_cpp11_safe_`, x_sxp)
}

string_proxy_assignment_ <- function() {
  .Call(`_cpp11test_string_proxy_assignment_`)
}

string_push_back_ <- function() {
  .Call(`_cpp11test_string_push_back_`)
}

sum_dbl_for_ <- function(x) {
  .Call(`_cpp11test_sum_dbl_for_`, x)
}

sum_dbl_for2_ <- function(x_sxp) {
  .Call(`_cpp11test_sum_dbl_for2_`, x_sxp)
}

sum_dbl_for3_ <- function(x_sxp) {
  .Call(`_cpp11test_sum_dbl_for3_`, x_sxp)
}

sum_dbl_foreach_ <- function(x) {
  .Call(`_cpp11test_sum_dbl_foreach_`, x)
}

sum_dbl_foreach2_ <- function(x_sxp) {
  .Call(`_cpp11test_sum_dbl_foreach2_`, x_sxp)
}

sum_dbl_accumulate_ <- function(x) {
  .Call(`_cpp11test_sum_dbl_accumulate_`, x)
}

sum_dbl_accumulate2_ <- function(x_sxp) {
  .Call(`_cpp11test_sum_dbl_accumulate2_`, x_sxp)
}

sum_int_for_ <- function(x) {
  .Call(`_cpp11test_sum_int_for_`, x)
}

sum_int_for2_ <- function(x_) {
  .Call(`_cpp11test_sum_int_for2_`, x_)
}

sum_int_foreach_ <- function(x) {
  .Call(`_cpp11test_sum_int_foreach_`, x)
}

sum_int_accumulate_ <- function(x) {
  .Call(`_cpp11test_sum_int_accumulate_`, x)
}

rcpp_sum_dbl_for_ <- function(x_sxp) {
  .Call(`_cpp11test_rcpp_sum_dbl_for_`, x_sxp)
}

rcpp_sum_int_for_ <- function(x_sxp) {
  .Call(`_cpp11test_rcpp_sum_int_for_`, x_sxp)
}

rcpp_sum_dbl_foreach_ <- function(x_sxp) {
  .Call(`_cpp11test_rcpp_sum_dbl_foreach_`, x_sxp)
}

rcpp_sum_dbl_accumulate_ <- function(x_sxp) {
  .Call(`_cpp11test_rcpp_sum_dbl_accumulate_`, x_sxp)
}

rcpp_grow_ <- function(n_sxp) {
  .Call(`_cpp11test_rcpp_grow_`, n_sxp)
}

rcpp_push_and_truncate_ <- function(size_sxp) {
  .Call(`_cpp11test_rcpp_push_and_truncate_`, size_sxp)
}

test_destruction_inner <- function() {
  invisible(.Call(`_cpp11test_test_destruction_inner`))
}

test_destruction_outer <- function() {
  invisible(.Call(`_cpp11test_test_destruction_outer`))
}

cpp11_push_and_truncate_ <- function(size_sexp) {
  .Call(`_cpp11test_cpp11_push_and_truncate_`, size_sexp)
}
