#' Generates wrappers for registered C++ functions
#'
#' Functions decorated with `[[cpp11::register]]` in files ending in `.cc`,
#' `.cpp`, `.h` or `.hpp` will be wrapped in generated code and registered to
#' be called from R.
#'
#' In order to use `cpp_register()` the `cli`, `decor`, `desc`, `glue`,
#' `tibble` and `vctrs` packages must also be installed.
#' @param path The path to the package root directory
#' @return The paths to the generated R and C++ source files (in that order).
#' @export
cpp_register <- function(path = ".") {
  stop_unless_installed(c("cli", "decor", "desc", "glue", "tibble", "vctrs"))

  r_path <- file.path(path, "R", "cpp11.R")
  cpp_path <- file.path(path, "src", "cpp11.cpp")
  unlink(c(r_path, cpp_path))

  suppressWarnings(
    all_decorations <- decor::cpp_decorations(path, is_attribute = TRUE)
  )

  if (nrow(all_decorations) == 0) {
    return(invisible(character()))
  }

  funs <- get_registered_functions(all_decorations, "cpp11::register")

  package <- desc::desc_get("Package", file = file.path(path, "DESCRIPTION"))

  cpp_functions_definitions <- generate_cpp_functions(funs, package)

  r_functions <- generate_r_functions(funs, package)

  dir.create(dirname(r_path), recursive = TRUE)

  writeLines(con = r_path, glue::glue('
      # Generated by cpp11: do not edit by hand

      {r_functions}

      '
  ))
  cli::cli_alert_success("generated file {.file {basename(r_path)}}")

  call_entries <- get_call_entries(path)

  cpp_function_registration <- glue::glue_data(funs, '    {{
    "_cpp11_{name}", (DL_FUNC) &_{package}_{name}, {n_args}}}, ',
    n_args = viapply(funs$args, nrow)
  )

  cpp_function_registration <- glue::glue_collapse(cpp_function_registration, sep  = "\n")

  extra_includes <-  character()
  if (pkg_links_to_rcpp(path)) {
    extra_includes <- c(extra_includes, "#include <cpp11/R.hpp>", "#include <Rcpp.h>", "using namespace Rcpp;")
  }

  pkg_types <- file.path(path, "src", paste0(package, "_types.h"))
  if (file.exists(pkg_types)) {
    extra_includes <- c(
      sprintf('#include "%s"', basename(pkg_types)),
      extra_includes
    )
  }

  extra_includes <- paste0(extra_includes, collapse = "\n")

  writeLines(con = cpp_path, glue::glue('
      // Generated by cpp11: do not edit by hand

      {extra_includes}
      #include "cpp11/declarations.hpp"

      {cpp_functions_definitions}

      extern "C" {{
      {call_entries}
      }}

      extern "C" void R_init_{package}(DllInfo* dll){{
        R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
        R_useDynamicSymbols(dll, FALSE);
      }}

      ',
      call_entries = glue::glue_collapse(call_entries, "\n")
  ))

  cli::cli_alert_success("generated file {.file {basename(cpp_path)}}")

  invisible(c(r_path, cpp_path))
}

utils::globalVariables(c("name", "return_type", "line", "decoration", "context", ".", "functions", "res"))

get_registered_functions <- function(decorations, tag) {
  if (NROW(decorations) == 0) {
    return(tibble::tibble(file = character(), line = integer(), decoration = character(), params = list(), context = list(), name = character(), return_type = character(), args = list()))
  }

  out <- decorations[decorations$decoration == tag, ]
  out$functions <- lapply(out$context, decor::parse_cpp_function, is_attribute = TRUE)
  out <- vctrs::vec_cbind(out, vctrs::vec_rbind(!!!out$functions))

  out <- out[!(names(out) %in% "functions")]
  out$decoration <- sub("::[[:alpha:]]+", "", out$decoration)

  cli::cli_alert_info(glue::glue("{n} functions decorated with [[{tag}]]", n = nrow(out)))

  out
}

generate_cpp_functions <- function(funs, package = "cpp11") {
  funs <- funs[c("name", "return_type", "args", "file", "line", "decoration")]
  funs$real_params <- vcapply(funs$args, glue_collapse_data, "{type} {name}")
  funs$sexp_params <- vcapply(funs$args, glue_collapse_data, "SEXP {name}")
  funs$calls <- mapply(wrap_call, funs$name, funs$return_type, funs$args, SIMPLIFY = TRUE)
  funs$package <- package

  out <- glue::glue_data(funs,
    '
    // {basename(file)}
    {return_type} {name}({real_params});
    extern "C" SEXP _{package}_{name}({sexp_params}) {{
      BEGIN_CPP11
      {calls}
      END_CPP11
    }}
    '
  )
  out <- glue::glue_collapse(out, sep = "\n")
  unclass(out)
}

generate_r_functions <- function(funs, package = "cpp11", use_package = FALSE) {
  if (use_package) {
    package_call <- glue::glue(', PACKAGE = "{package}"')
  } else {
    package_call <- ""
  }

  funs <- funs[c("name", "return_type", "args")]
  funs$package <- package
  funs$package_call <- package_call
  funs$list_params <- vcapply(funs$args, glue_collapse_data, "{name}")
  funs$params <- vcapply(funs$list_params, function(x) if (nzchar(x)) paste0(", ", x) else x)
  is_void <- funs$return_type == "void"
  funs$calls <- ifelse(is_void,
    glue::glue_data(funs, 'invisible(.Call("_{package}_{name}"{params}{package_call}))'),
    glue::glue_data(funs, '.Call("_{package}_{name}"{params}{package_call})')
  )

  out <- glue::glue_data(funs, '
    {name} <- function({list_params}) {{
      {calls}
    }}
    ')
  out <- glue::glue_collapse(out, sep = "\n\n")
  unclass(out)
}

wrap_call <- function(name, return_type, args) {
  call <- glue::glue('{name}({list_params})', list_params = glue_collapse_data(args, "cpp11::unmove(cpp11::as_cpp<{type}>({name}))"))
  if (return_type == "void") {
    unclass(glue::glue("  {call};\n    return R_NilValue;", .trim = FALSE))
  } else {
    unclass(glue::glue("  return cpp11::as_sexp({call});"))
  }
}

get_call_entries <- function(path) {
  con <- textConnection("res", open = "w")

  try(
    tools::package_native_routine_registration_skeleton(path,
      con,
      character_only = FALSE,
      include_declarations = TRUE
    ),
    silent = TRUE
  )

  close(con)

  start <- grep("/* .Call calls */", res, fixed = TRUE)
  end <- grep("};", res, fixed = TRUE)

  if (length(start) == 0) {
    return("")
  }
  res[seq(start, end)]
}

pkg_links_to_rcpp <- function(path) {
  deps <- desc::desc_get_deps(file.path(path, "DESCRIPTION"))

  any(deps$type == "LinkingTo" & deps$package == "Rcpp")
}
